# Start a few existing instances, run some tasks

- name: Start sandbox instances
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  vars:
    instance_ids:
      - 'i-90b43c76'
      - 'i-c348c025'
    region: eu-west-1a
  tasks:
    - name: Start the sandbox instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: running
        wait: True
        vpc_subnet_id: subnet-a48f5ffd
        assign_public_ip: yes
  role:
    - do_neat_stuff
    - do_more_neat_stuff
