# Stop the instances

- name: Stop sandbox instances
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  vars:
    instance_ids:
      - 'i-90b43c76'
    region: eu-west-1a
  tasks:
    - name: Stop the sandbox instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: stopped
        wait: True
        vpc_subnet_id: subnet-a48f5ffd
        assign_public_ip: yes